# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
workspace 'SafeKeyboard.xcworkspace'
inhibit_all_warnings!

target 'SafeKeyboard' do
    use_frameworks!
    pod 'SnapKit'
    pod 'CYRKeyboardButton'
end
